---
language: python
python: '2.7'
before_install:
- sudo apt-get update -qq
- pip install --upgrade pip
install:
- pip install ansible
- mv test/ansible.cfg.example ansible.cfg
script:
- ansible-playbook -i test/inventory test/travis.yml --syntax-check
- ansible-playbook -i test/inventory test/travis.yml --connection=local --sudo
- >
  ansible-playbook -i test/inventory test/travis.yml --connection=local --sudo
  | grep -q "changed=1.*failed=0"
  && (echo 'Idempotence test: pass' && exit 0)
  || (echo 'Idempotence test: fail' && exit 1)
notifications:
  webhooks:
    urls:
      secure: I8e7XqOk1/DCONJIWrr1ZWc3nHuOVOsORB1dkUcrjHycq+S6l86OC9rp9V+H4ylV0b7bVipZhiGeFuw/MGSW6sOg81DFq0i5qyQI9i/e7yvLsCxXIN/KKqN+4TNvryzfNRhB/HqadINYHevo4Ln31mNdE2r4Pd70pgU3Cjswvvo=
