- name:       Install dependencies
  sudo:       true
  apt:        pkg={{item}} state=present install_recommends=no
  with_items:
              - build-essential
              - git
              - libcurl4-openssl-dev
              - libmysqlclient-dev
              - libreadline6-dev
              - libssl-dev
              - libxml2-dev
              - libxslt1-dev
              - ruby-dev
              - zlib1g-dev
