---
- include:       dependencies.yml
  when:          ruby_build_install_dependencies

- name:          Check current installation
  shell:         ruby-build --version
  ignore_errors: true
  register:      ruby_build_already_installed

- name:          Create root directory
  file:          path={{ ruby_build_root }} state=directory
  register:      ruby_build_root_created

- name:          Install
  git:           repo=https://github.com/sstephenson/ruby-build.git
                 dest={{ ruby_build_root }}
                 update=yes
                 version={{ ruby_build_version }}
  when:          ruby_build_already_installed|failed or
                 ruby_build_root_created|changed or
                 ruby_build_version == "master" or
                 ruby_build_already_installed.stdout | replace("ruby-build", "") != ruby_build_version
  register:      ruby_build_installed

- name:          Add binary to $PATH
  sudo:          true
  file:          path=/usr/local/bin/ruby-build
                 src={{ ruby_build_root }}/bin/ruby-build
                 state=link
  when:          ruby_build_installed|changed

- include:       extras.yml
